### ISSUE TITLE
Learning to Rank

### ISSUE THREAD

**Issue by ssrisunt** [cog-imperial/OMLT#100]
Is it possible to use OMLT in learning to rank? if so , please provide example.

Thanks

**Comment by rmisener** [comment]
If I've understood the question properly, the application of "learning to rank" is described by this Wikipedia article: https://en.wikipedia.org/wiki/Learning_to_rank

If this is what @ssrisunt means, then no, OMLT is probably not applicable. The Wikipedia article describes a machine learning approach that develops a prediction. OMLT does not develop a prediction model: it uses an already-existing prediction model trained from data and then makes optimal decisions over that training model.
