### ISSUE TITLE
Error while reading onnx file

### ISSUE THREAD

**Issue by hhijazi** [cog-imperial/OMLT#103]
When I call the function `net = load_onnx_neural_network(model)` with the attached onnx file, I get the following error:
`File "/usr/local/lib/python3.10/site-packages/omlt/io/onnx_parser.py", line 235, in _consume_gemm_dense_nodes
    assert attr["transB"] == 1
AssertionError`
[MatMul_Add_Sim.onnx.zip](https://github.com/cog-imperial/OMLT/files/11265476/MatMul_Add_Sim.onnx.zip)

**Comment by jalving** [comment]
Thanks for reporting this. We seem to be having a few issues with loading ONNX files. It is likely we will need to revisit the ONNX reader.

**Comment by juan-campos** [comment]
@hhijazi This bug has been fixed in PR #121 which we have now merged.
