### ISSUE TITLE
Error building MIP model from ONNX file

### ISSUE THREAD

**Issue by hhijazi** [cog-imperial/OMLT#104]
I get the following error when trying to read the attached onnx file:
`  File "/usr/local/lib/python3.10/site-packages/omlt/neuralnet/activations/relu.py", line 51, in bigm_relu_activation_constraint
    layer_block.z[output_index].setub(max(0, ub))
TypeError: '>' not supported between instances of 'NoneType' and 'int'`
[MatMul_Add.onnx.zip](https://github.com/cog-imperial/OMLT/files/11265493/MatMul_Add.onnx.zip)

**Comment by tsaycal** [comment]
Thanks for the question @hhijazi. My colleague @juan-campos has tried:
```
onnx_model = onnx.load(‘MatMul_Add.onnx’)
network_definition = load_onnx_neural_network(onnx_model)
```
without getting issues. Are you including variable bounds? Perhaps the issue is with these.

**Comment by hhijazi** [comment]
I did the following:
```
model = onnx.load("MatMul_Add.onnx")

net = load_onnx_neural_network(model)

formulation = FullSpaceNNFormulation(net)

mip = pyo.ConcreteModel()

mip.nn = OmltBlock()

mip.nn.build_formulation(formulation)
```

**Comment by hhijazi** [comment]
Ok, thanks Juan! It would be nice to specify this in the doc or the Readme, or perhaps I just missed it...
