### ISSUE TITLE
Importing a Pytorch neural network with tanh activation using ONNX does not work.

### ISSUE THREAD

**Issue by caelorza** [cog-imperial/OMLT#109]
Using Tanh as an activation function returns the following error. Using other activation functions such as sigmoid or relu works fine.
```python
Exception: Unhandled node type Tanh
``` 
ONNX version: 1.13.1
OMLT version: 1.1
Pytorch version: 2.0.1

```python
import torch
from torch import nn
from collections import OrderedDict


from omlt.io import write_onnx_model_with_bounds, load_onnx_neural_network_with_bounds
from omlt import OmltBlock, OffsetScaling
from omlt.neuralnet import FullSpaceNNFormulation, NetworkDefinition

import tempfile

if torch.cuda.is_available():
    device = torch.device('cuda')
    print("Running on GPU")
else:
    device = torch.device('cpu')
    print("Running on CPU")
    
class DNN(nn.Module):
    def __init__(
        self, n_in, n_out, n_neu, n_layers, activ="Tanh"
    ):
        super().__init__()
            
        self.n_in = n_in
        self.n_out = n_out
        self.n_neu = n_neu
        self.n_layers = n_layers
        self.activ = getattr(nn, activ)
        
        layer_list =list()

        layer_list.append(
            ('layer_%d' % 0, nn.Linear(self.n_in, self.n_neu))
        )
        
        layer_list.append(
            ('activation_%d' % 0, self.activ())
        )
        
        for i in range(1,self.n_layers):
            
            layer_list.append(
                ('layer_%d' % i,nn.Linear(self.n_neu, self.n_neu))
            )
            
            
            layer_list.append(
                ('activation_%d' % i, self.activ())
            )
        
        layer_list.append(
            ('layer_%d' % n_layers, nn.Linear(self.n_neu, self.n_out))
        )
        
        layerDict = OrderedDict(layer_list)
        
        self.dnn = nn.Sequential(layerDict)

    def forward(self, x):
        return self.dnn(x)
    
    
if __name__=="__main__":
    
    n_in = 2
    n_out = 2
    n_neu = 5
    n_layers = 3
    
    model = DNN(n_in,n_out,n_neu,n_layers,activ="Tanh").to(device)
    
    x = torch.randn(10, n_in, requires_grad=True).to(device)
    pytorch_model = None
    with tempfile.NamedTemporaryFile(suffix='.onnx', delete=False) as f:
        torch.onnx.export(
            model,
            x,
            f,
            input_names=['input'],
            output_names=['output'],
            dynamic_axes={
                'input': {0: 'batch_size'},
                'output': {0: 'batch_size'}
            }
        )
        
    input_bounds = [(-1, 1) for _ in range(n_in)]
    write_onnx_model_with_bounds(f.name, None, input_bounds)
    print(f"Wrote PyTorch model to {f.name}")
    pytorch_model = f.name
    
    network_definition = load_onnx_neural_network_with_bounds(pytorch_model)

```

**Comment by caelorza** [comment]
{
	"name": "Exception",
	"message": "Unhandled node type Tanh",
	"stack": "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mException\u001b[0m                                 Traceback (most recent call last)\n\u001b[1;32mc:\\Users\\candr\\OneDrive\\Desktop\\zip\\SampleNN.py\u001b[0m in \u001b[0;36mline 93\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/OneDrive/Desktop/zip/SampleNN.py?line=89'>90</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mWrote PyTorch model to \u001b[39m\u001b[39m{\u001b[39;00mf\u001b[39m.\u001b[39mname\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/OneDrive/Desktop/zip/SampleNN.py?line=90'>91</a>\u001b[0m pytorch_model \u001b[39m=\u001b[39m f\u001b[39m.\u001b[39mname\n\u001b[1;32m---> <a href='file:///c%3A/Users/candr/OneDrive/Desktop/zip/SampleNN.py?line=92'>93</a>\u001b[0m network_definition \u001b[39m=\u001b[39m load_onnx_neural_network_with_bounds(pytorch_model)\n\nFile \u001b[1;32mc:\\Users\\candr\\anaconda3\\envs\\TorchPyomo\\lib\\site-packages\\omlt\\io\\onnx.py:52\u001b[0m, in \u001b[0;36mload_onnx_neural_network_with_bounds\u001b[1;34m(filename)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=48'>49</a>\u001b[0m \u001b[39mif\u001b[39;00m input_bounds_filename\u001b[39m.\u001b[39mexists:\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=49'>50</a>\u001b[0m     input_bounds \u001b[39m=\u001b[39m load_input_bounds(input_bounds_filename)\n\u001b[1;32m---> <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=51'>52</a>\u001b[0m \u001b[39mreturn\u001b[39;00m load_onnx_neural_network(onnx_model, input_bounds\u001b[39m=\u001b[39;49minput_bounds)\n\nFile \u001b[1;32mc:\\Users\\candr\\anaconda3\\envs\\TorchPyomo\\lib\\site-packages\\omlt\\io\\onnx.py:71\u001b[0m, in \u001b[0;36mload_onnx_neural_network\u001b[1;34m(onnx, scaling_object, input_bounds)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=55'>56</a>\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=56'>57</a>\u001b[0m \u001b[39mLoad a NetworkDefinition from an onnx object.\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=57'>58</a>\u001b[0m \n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=67'>68</a>\u001b[0m \u001b[39mNetworkDefinition\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=68'>69</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=69'>70</a>\u001b[0m parser \u001b[39m=\u001b[39m NetworkParser()\n\u001b[1;32m---> <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx.py?line=70'>71</a>\u001b[0m \u001b[39mreturn\u001b[39;00m parser\u001b[39m.\u001b[39;49mparse_network(onnx\u001b[39m.\u001b[39;49mgraph, scaling_object, input_bounds)\n\nFile \u001b[1;32mc:\\Users\\candr\\anaconda3\\envs\\TorchPyomo\\lib\\site-packages\\omlt\\io\\onnx_parser.py:131\u001b[0m, in \u001b[0;36mNetworkParser.parse_network\u001b[1;34m(self, graph, scaling_object, input_bounds)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=128'>129</a>\u001b[0m \u001b[39m# no need to process inputs or outputs\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=129'>130</a>\u001b[0m \u001b[39mif\u001b[39;00m type_ \u001b[39m==\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mnode\u001b[39m\u001b[39m\"\u001b[39m:\n\u001b[1;32m--> <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=130'>131</a>\u001b[0m     new_layer, new_layer_inputs \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_visit_node(node, next_nodes)\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=131'>132</a>\u001b[0m     \u001b[39mif\u001b[39;00m new_layer \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=132'>133</a>\u001b[0m         network\u001b[39m.\u001b[39madd_layer(new_layer)\n\nFile \u001b[1;32mc:\\Users\\candr\\anaconda3\\envs\\TorchPyomo\\lib\\site-packages\\omlt\\io\\onnx_parser.py:163\u001b[0m, in \u001b[0;36mNetworkParser._visit_node\u001b[1;34m(self, node, next_nodes)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=158'>159</a>\u001b[0m     next_nodes, new_layer, new_layer_inputs \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_consume_pool_nodes(\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=159'>160</a>\u001b[0m         node, next_nodes\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=160'>161</a>\u001b[0m     )\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=161'>162</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=162'>163</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mException\u001b[39;00m(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mUnhandled node type \u001b[39m\u001b[39m{\u001b[39;00mnode\u001b[39m.\u001b[39mop_type\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=164'>165</a>\u001b[0m \u001b[39mfor\u001b[39;00m \u001b[39mnext\u001b[39m \u001b[39min\u001b[39;00m next_nodes:\n\u001b[0;32m    <a href='file:///c%3A/Users/candr/anaconda3/envs/TorchPyomo/lib/site-packages/omlt/io/onnx_parser.py?line=165'>166</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_node_stack\u001b[39m.\u001b[39mappend(\u001b[39mnext\u001b[39m)\n\n\u001b[1;31mException\u001b[0m: Unhandled node type Tanh"
}

**Comment by zzygith** [comment]
I meet the same question. I don't find Tanh in _ACTIVATION_OP_TYPES of onnx_parser.py. Do you have any clue now?

**Comment by rmisener** [comment]
@juan-campos fixed this bug in PR https://github.com/cog-imperial/OMLT/pull/121, which we've now merged. Would you take a look and see if this solves your problem? @juan-campos also added some tests to try to make sure we don't reintroduce this bug!

**Comment by zzygith** [comment]
The problem has been solved. Thanks for wonderful work.
