### ISSUE TITLE
LightGBM Linear Tree

### ISSUE THREAD

**Issue by mu-wang** [cog-imperial/OMLT#162]
LightGBM offers linear tree implementation: https://lightgbm.readthedocs.io/en/latest/Parameters.html#dataset-parameters
Will OMLT work for the onnx model exported from LightGBM linear tree?

**Comment by rmisener** [comment]
No, unfortunately not, the linear tree IO is different than the other models in OMLT. Take a look at the Jupyter notebook to see what input/output approaches work with linear trees. We're working on making the tree-related IO more sensible in OMLT (let us know if you want to help!), but it's not ready.
