### ISSUE TITLE
Mixing ReLU and non-linear activation functions

### ISSUE THREAD

**Issue by fracek** [cog-imperial/OMLT#19]
We discussed that generating formulations that introduce MIP constraints for ReLU and non-linear constraints for other activations should not be possible. OMLT should throw and exception in this case.

**Comment by jalving** [comment]
The new formulations as of PR #33 should fix this. `ReluBigMFormulation` will not allow nonlinear activation functions, but a user can certainly try to mix activations using `FullspaceNNFormulation`.
