### ISSUE TITLE
Complete testing for gbt

### ISSUE THREAD

**Issue by carldlaird** [cog-imperial/OMLT#27]
reminder to finish this test

_Originally posted by @jalving in https://github.com/cog-imperial/OMLT/pull/24#discussion_r784130787_

**Comment by rmisener** [comment]
@fracek, Possible to add the tests you identified where OMLT was previously failing with @ThebTron examples? 

Other than that, this issue is mostly addressed by PR #30

**Comment by rmisener** [comment]
@carldlaird, okay to close this one now?
