### ISSUE TITLE
Dependencies - ONNX and TensorFlow

### ISSUE THREAD

**Issue by rmisener** [cog-imperial/OMLT#52]
The ONNX reader requires ONNX and the Keras reader needs tensorflow.keras. We need better and more descriptive error handling to manage this.

**Comment by carldlaird** [comment]
Pyomo has a reasonable system for conditional importing. @jalving and I could look at this. I prefer not to have a growing list of dependencies.

**Comment by rmisener** [comment]
Agreed and thanks.
