### ISSUE TITLE
Host docs

### ISSUE THREAD

**Issue by DavidWalz** [cog-imperial/OMLT#66]
As far as I can tell from (repo, pypi & actions) the sphinx documentation is not hosted yet. Having the docs hosted on e.g. readthedocs would significantly help adoption.

**Comment by jalving** [comment]
You can get to the current readthedocs using the doc badge on the README. It should take you here: https://omlt.readthedocs.io/en/latest/?badge=latest. Most 

Perhaps it would be better to explicitly link to the documentation from the README.

**Comment by DavidWalz** [comment]
I'm blind. Thanks for the pointer!
