### ISSUE TITLE
Copyright in documentation

### ISSUE THREAD

**Issue by fracek** [cog-imperial/OMLT#9]
At the moment, the documentation copyright is set to me since that's the default used by the template. What should we change that to to give credit to the COG Group, Sandia, and CMU?

**Comment by jalving** [comment]
I think what you have now `"2021, Carnegie Mellon University, Imperial College London, Sandia National Laboratories"` is sufficient (maybe update to 2022?). 

@carldlaird: Do you see any issues with this?

**Comment by jalving** [comment]
Fixed by PR #44
